### ISSUE TITLE
[dsub] Handle supporting / not supporting querying by status-detail

### ISSUE THREAD

**Issue by alahwa** [DataBiosphere/job-manager#168]

**Comment by bfcrampton** [comment]
This doesn't affect all labels, just `user-id`, `status-detail`, and `last-update`. For example, querying by the `test_token` label will work: 

[`http://localhost:4200/jobs?q=parent-id%3Dbvdp-jmui-testing%26job-name%3Djob1%26test_token%3D20180103_101707_582388`](http://localhost:4200/jobs?q=parent-id%3Dbvdp-jmui-testing%26job-name%3Djob1%26test_token%3D20180103_101707_582388)

The fields which do not work are not real "labels" in `dsub`, we just add them as labels in the common API because that is basically the dumping ground for fields which are not first-class citizens. `dstat` does not support filtering by `status-detail` or `last-update` and thus this will have to be done either in the shim or client-side. It does support filtering by `user-id` (but not as a label), which I've separated into #169. 

See the `dstat` interface [here](https://github.com/googlegenomics/dsub/blob/master/dsub/commands/dstat.py#L440).

I think the question now is whether or not we should support filtering by these other fields which we jam into the API as labels. I do not think `status-detail` makes sense to query by, since that can often contain a stack trace and be multi-line, i.e.:
```
11: Docker run failed: command failed: /mnt/data/script/not_a_command: line 2: not_a_command: command not found . See logs at gs://bvdp-jmui-testing/google/logging/
```

The easiest fix for now seems to be expanding the column configuration to allow specifying columns which **cannot** be filtered by, and prevent users from entering those field names.

**Comment by alahwa** [comment]
Since we want to keep the UI as decoupled from the backend as possible, the client should only ever have to know about the existence of primary fields and labels. Any implementation details beyond that should be handled in the dsub shim.

Inevitably, users will expect to be able to query over the fields that are visible to them in the client, including status-detail, user-id, and last-update. For user-id, we could handle this in the shim by translating the request and moving the user-id from the label map to a first order field.

For status-detail and last-update it'll be trickier, but I still think it's important to preserve the UX of being able to search over fields that you see. I think we should either choose to:
- display the information in the table and provide a dsub implementation for filtering over those fields
- not display the information and also not provide a dsub implementation

Ideally, we would want to be able to regex filter over something like status-detail. This could be a powerful use case for users looking to find something like all of the jobs with similar failure types (in the case of this field containing stack traces).

**Comment by bfcrampton** [comment]
> Since we want to keep the UI as decoupled from the backend as possible, the client should only ever have to know about the existence of primary fields and labels. Any implementation details beyond that should be handled in the dsub shim.

I think inevitably this will not be the case--there will be things visible in the UI which are not queryable in the shim. `status-detail` is different than the queryable fields in that it contains free, multi-line text which is often a stack trace. It is a convenience field which reflects the same information present in the job's controller log file, but it is not something which would naturally be queried by, just as you cannot query by the contents of a job's log file. From a technical perspective, it will be impossible to implement querying by 'status-detail' in the shim, because it is computed in dstat and thus would require retrieving every job in a given project, since its beginning. Our users have projects containing millions of jobs so this is infeasible.


> Inevitably, users will expect to be able to query over the fields that are visible to them in the client, including status-detail, user-id, and last-update. For user-id, we could handle this in the shim by translating the request and moving the user-id from the label map to a first order field.

`user-id` is a simple string field which I definitely makes sense to be able to query by. As I mentioned, I separated this out into a separate bug to fix: #169.

I do not think this is true for fields containing long multi-line text blocks, like `status-detail` and `_SCRIPT`. I doubt users will have the expectation of being able to query by these fields since they are  basically convenience fields so that they don't have to open the log or script file. I also do not think there is any way a regex based searching over these could be implemented with the pipelines API as a back end.



I think the two options we have are:
1. Allow general specification of fields which are not queryable. This doesn't mean coupling the UI to a specific backend, but just expanding the column configuration to indicate fields which cannot be searched over.
1. Not display these convenience fields to the user, so they won't have any expectation to be able to query by it. 

I am more inclined towards 1 since that we way we are still providing all the information we can to the user, which is valuable. However, if you think that will be sufficiently confusing we could remove those fields from the column config file.

**Comment by bfcrampton** [comment]
`last-update` is a bit different of a case and I could see it being handled in the shim. I moved this task into https://github.com/DataBiosphere/job-manager/issues/73 since it will have an almost identical implementation as adding support for `end-time` querying in the shim.

**Comment by alahwa** [comment]
In this case, I think it probably makes the most sense to remove the status-detail label from the table view (since this implies a field:value relationship that should be queryable) and possibly move that information to the details view. If they are expected to be long strings, the table format doesn't convey this well anyway, and that way users aren't frustrated that they can't query those fields.

**Comment by bfcrampton** [comment]
I think that makes sense actually since status-detail can often be cut off in the table view anyways (since it's multiline text but is displayed on a single line).

**Comment by bfcrampton** [comment]
The script text will likely only be on the detail page too so I a good strategy may be to just limit fields displayed on the table view to those which can be queried by.

**Comment by alahwa** [comment]
The only issue is that we are then modifying the UI directly based on labeled fields, which then couples the UI with the backend again. Is it possible to define these fields directly in the API and allow them to be optional for Cromwell instead?

**Comment by bfcrampton** [comment]
Sorry I'm not sure I understand. We are already configuring the displayed columns using an environment config that is specific to dsub/cromwell. Can't we just want to remove `status-detail` [here](https://github.com/DataBiosphere/job-manager/blob/master/ui/src/environments/environment.dsub.google.ts#L8) and [here](https://github.com/DataBiosphere/job-manager/blob/master/ui/src/environments/environment.dsub.local.ts#L7)?

**Comment by alahwa** [comment]
Yes, but if we want to add that field to, for instance, the details page, then we'll need to hard code into the UI to reach into the labels and extract 'status-detail' which defeats the purpose of allowing labels to be entirely config-driven. So practically speaking, we'd be treating this field like a field from the API. If that's the case, could we just formally add it to the API?

**Comment by bfcrampton** [comment]
Right now we are showing all labels on the detail page regardless. So I don't think it needs to be treated any differently than any other arbitrary labels (e.g. `test_token` is a label we always add to our integration test jobs). I'm proposing we just remove `status-detail` from the column config but still treat it as a label on detail page (which is different than API fields).

<img width="620" alt="screen shot 2018-01-03 at 12 18 21 pm" src="https://user-images.githubusercontent.com/1890623/34538164-3583510a-f080-11e7-8bb2-2be17b1041c9.png">

**Comment by alahwa** [comment]
Ah ok I didn't realize the list of labels on the details view was separate, yeah then just removing it from the config should work.

**Comment by alahwa** [comment]
#171

**Comment by calbach** [comment]
Separately, my injection of the fake `status-detail` label was a bit of a breakage of the API contract. In the API it will show up as a label, and yet it is not queryable as a label.

We should consider incorporating `statusDetail` as a top-level API field on the job, or else add a dumping grounds field like `serverLabels` / `backendLabels` / `generatedLabels` to put these kinds of things where they won't be conflated with user labels. Will raise tomorrow at standup.
