### ISSUE TITLE
When clicking on a Failed workflow you only show completed tasks in list but not the failed task.

### ISSUE THREAD

**Issue by hjfbynara** [DataBiosphere/job-manager#268]
I may be missing something, but I would think especially for failed workflows that you would want have in the list all the failed tasks (assuming a failed task was why the workflow failed - which I am pretty sure is usually the case).  This way you can more easily see which task failed.

**Comment by kbergin** [comment]
Hi @hjfbynara - We definitely would want to see the failed task for a failed workflow! Do you happen to recall a workflow where you saw this failure? In the ones I can find, the failed task usually looks like this: 
![image](https://user-images.githubusercontent.com/9449764/39725384-8b19aea2-5219-11e8-82a7-67549be3d427.png)

Example is from a mint cromwell (allowed to be public) but I am seeing the same thing in gotc-prod. We currently have an issue where Cromwell workflows that fail before they get metadata attached to them show up in the UI with no information. I wonder if a similar thing happens if a task fails before it actually starts? I'd love to dig into this further if you know of an example. Happy to chat offline as well. Thank you!

**Comment by kbergin** [comment]
Oh, also possible that there was a failure in a scattered task where not all scatters failed? We are not handling scatters well at all right now (they look like one line of a task and it's only representing the first shard) so this could be a hidden failure. We plan to handle scattered tasks better very soon!

**Comment by rsasch** [comment]
@kbergin @hjfbynara Is this still an issue with the most recent version of JM, which handles scattered tasks?

**Comment by kbergin** [comment]
I think to recreate it, you would need to run a job with a scattered task and have one of the shards fail. The task listed (which represents the scattered task) should show failed if more than 0 of the shards failed, I think, and the failed shard should go to the error panel. Does that make sense? I don't have a workflow off hand where I've observed this/can look back and find it quickly, but if you have tested that already or know you designed it to handle this use case, I would think this is all set.

I'd be interested in seeing how that looks out of curiosity if you have a test workflow that shows how that is handled.

**Comment by rsasch** [comment]
@kbergin Here is a workflow with two tasks, one is scattered and nine of the shards in that task have failed.
![screen shot 2018-10-17 at 12 11 58 pm](https://user-images.githubusercontent.com/1713505/47100641-fe6c9b00-d205-11e8-83ac-c88ac3e48766.png)
Does that help?

**Comment by kbergin** [comment]
That's perfect! Looks great to me. I think this is resolved.

**Comment by rsasch** [comment]
Great – thank you for the quick responses!
