### ISSUE TITLE
Error Panel for "Failures"

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#317]
For failed jobs (ie workflows to Cromwell):
- [ ] Add an `errors` panel to pass through details about jobs which didn't succeed
- [ ] For this ticket, the `errors` panel should find a list of "Failures" relating to the job and display them (doesn't need to be pretty for now, just make it visible!)

**Comment by rsasch** [comment]
@geoffjentry @ruchim One of the Cromwell API responses of interest in https://github.com/broadinstitute/cromwell/issues/2533 is the way failure messages are returned from the metadata input. Should this issue wait until that is resolved?

**Comment by rsasch** [comment]
@ruchim We need a design for this because it's not clear where it would make sense to put these errors in the current wireframe for the task details page:

<img width="1066" alt="screen shot 2018-07-25 at 10 32 41 am" src="https://user-images.githubusercontent.com/1713505/43207462-2792b14c-8ff6-11e8-850d-3d514c32b306.png">

**Comment by geoffjentry** [comment]
@rsasch Waiting for that endpoint to get fixed is likely to take longer than you can afford to hold tight. If there's a particular thing you need cleaned up let us know what needs to change and how it needs to change and we can try to do that piece specifically

**Comment by rsasch** [comment]
@geoffjentry It turns out this issue also needs some design work, so it's stalled either way.

**Comment by geoffjentry** [comment]
okee doke

**Comment by rsasch** [comment]
**Blocked**: need design spec for where to put this information on the job details page.

**Comment by cjllanwarne** [comment]
@rsasch I think it make sense as a first-pass to get the workflow level error messages (ie ignore the `causedBy`s and the task-specific error messages for now) and put them into a separate tile next to the `Status` tile (just like in the mockup).

That won't have the links to "stdout" and "stderr" if they reference tasks (like the mockup does), but I think that's ok because that's what the "Tasks" list is for.

**Comment by kbergin** [comment]
As Bec noted, we would still like to see the failed tasks together with their logs. Putting the error message in could also be an option, I don't see why it couldn't be another icon next to all the tasks that we make show the error message on hover over? We should see what Marty suggests on where/how to show that information. In addition, I believe this is covered in the ticket migrated from the elastc backlog: #353

**Comment by cjllanwarne** [comment]
@kbergin if we put the task-level error messages in the task list, could we use the "errors" panel here as suggested above (ie for workflow-level error messages) and rely on the tasks list to show task-level error messages?

**Comment by kbergin** [comment]
@cjllanwarne I'm not sure what this ticket is, looks like you put it in. The quarterly goal around quick identification of failures was in reference to the user story in #349 . This ticket has nothing to do with error messages and is only a way to bring failed tasks up to the users attention instead of interspersed with the tasks below.

A feature we had in the backlog that is more similar to this ticket is #353 and refers to finding a way to show the error messages. I think this is a duplicate ticket of that one, and we do not yet have a design for how/where to show these error messages.

**Comment by cjllanwarne** [comment]
Seems like the following are all potential ACs that right now are split across a bunch of different tickets:

  - Show the tasks that failed on a "job details" page
  - Show the error messages of tasks that failed (on the job details page)
  - Show the error messages of tasks that failed (on the task details page)
  - Show the error messages of workflows that failed

**Comment by kbergin** [comment]
@cjllanwarne Kind of, we don't have a ticket about task error messages being on a task details page.. we don't have a task details page right now.

**Comment by rsasch** [comment]
closed in favor of #451
