### ISSUE TITLE
Make the status of the root workflow more obvious.

### ISSUE THREAD

**Issue by tlangs** [DataBiosphere/job-manager#541]
<img width="1403" alt="screen shot 2019-01-08 at 3 11 54 pm" src="https://user-images.githubusercontent.com/3210510/50856449-be2a3e00-1358-11e9-948e-468a35aeeeac.png">
Pretty much just what the picture says. Reading a small bit of text underneath the main workflow name text is non-obvious. It requires the parsing of 3 distinct states to suss out what the state of the root workflow is. A large, obvious icon or large status text after the name of the root workflow would greatly help readability at a glance.

**Comment by martygardner** [comment]
I agree with having the single summary status in one place instead of having to parse the 3 tasks statuses. But I would probably put that status in the card devoted to that information rather than floating at the very top.

##Status
[icon] Running
Tasks: 2 succeeded, 0 failed...

or 

##Status: Running [icon]
Tasks: 2 succeeded, 0 failed...

**Comment by rsasch** [comment]
@tlangs @martygardner How about this?
![status-icon-in-card](https://user-images.githubusercontent.com/1713505/51203965-78c5bd80-18d0-11e9-83ff-3d089e04d7b8.png)

**Comment by martygardner** [comment]
Perfect!
