### ISSUE TITLE
Filter by numeric-starting workflow ID fails

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#584]
To reproduce:

 * Open the job list
 * Find a workflow with an ID starting with a number
* In the query bar start typing "workflow" to choose the option "Workflow ID"
* Enter the workflow ID with a number at the start

An error appears, eg:

<img width="579" alt="Screen Shot 2019-03-11 at 7 18 33 PM" src="https://user-images.githubusercontent.com/13006282/54164308-8ad85e00-4432-11e9-9b19-323a6f392efc.png">

**Comment by cjllanwarne** [comment]
This is presumably because "workflow ID" used to be a label, and label names used to (still do?) have that constraint

**Comment by barkasn** [comment]
I have come across this as well. @rexwangcc found that the error is at https://github.com/DataBiosphere/job-manager/blob/1cdfc7c2542b64e311b3271b44b124e7435517b8/api/jobs.yaml#L399

This is a hindrance when trying to find a run, please fix.

**Comment by rexwangcc** [comment]
@cjllanwarne > This is presumably because "workflow ID" used to be a label, and label names used to (still do?) have that constraint

That can explain why we haven't found this until recently. The label shadows the problematic regex around workflow id definition. Not sure if this regex only works for dsub.
