### ISSUE TITLE
Missing task name from timing diagram

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#604]
Can't see my task name from the timing diagram at all. This seems like a bug.

<img width="1313" alt="Screen Shot 2019-03-24 at 10 57 12 PM" src="https://user-images.githubusercontent.com/14941133/54892512-37c9c680-4e88-11e9-8975-1fbef607a55d.png">

AC: Re-add some kind of notation to explain which row of the timing diagram belongs to which task.

**Comment by rsasch** [comment]
There is a property in the Google `timeline` chart that will display labels for each row.  Unfortunately, it cuts off the names so that they are illegible.  This is a known issue (see https://groups.google.com/forum/#!topic/google-visualization-api/JXYbWNAEsYU).

**Comment by ruchim** [comment]
Can we get the names on the bar itself?

**Comment by rsasch** [comment]
Because each bar is broken up into events, the text that would be displayed (if that option was turned on) on the bar, would be of each event, not the task (see https://developers.google.com/chart/interactive/docs/gallery/timeline#an-advanced-example, although, like with the row labels, the display within Angular is not as readable as the documentation would lead you to expect).

**Comment by ruchim** [comment]
@rsasch -- I believe one can get the task name now by hovering over the bar? if yes, let's close this issue.

**Comment by rsasch** [comment]
Yes, when you mouseover a bar, you see the event name and the task name.
